namespace Math
{
	extern const int RANDMAX;
	float sqrt(float f);
	int sqrti(int i);
	float sqr(float f);
	float VectorLen(float x, float y, float z);
	void NormalizeVector(float &x, float &y, float &z);
	int rand();
	int abs(int i);
    float acos(float f);
    float asin(float f);
    float atan(float f);
    float atan2(float f, float g);
    float cos(float f);
    float cosh(float f);
   float exp(float f);
   float fabs(float f);
   float fmod(float f, float g);
   float log(float f);
   float log10(float f);
   float pow(float f, float g);
   float sin(float f);
   float sinh(float f);
   float tan(float f);
   float tanh(float f);
	float atof(const char *s);
	int atoi(const char *s);
	float ceil(float f);
	float floor(float f);
	float dist2(float x0, float y0, float x1, float y1);
	float dist(float x0, float y0, float x1, float y1);
	float dist2(float x0, float y0, float z0, float x1, float y1, float z1);
	float dist(float x0, float y0, float z0, float x1, float y1, float z1);
	void RotateVector(float &vectorx_, float &vectory_, float &vectorz_, const float *matrix3x3_);
	void CrossProduct(float x, float y, float z, float &cx, float &cy, float &cz);
	void EulerToMatrix(float yaw, float pitch, float roll, float *matrix3x3_);
	void MultiplyMatrices(float *mat1_, const float *mat2_);
};